version: '3.7'
services:
  zookeeper:
    image: wurstmeister/zookeeper:3.4.6
    # ports:
    #   - '2181:2181'
    networks:
      kf_net:
        ipv4_address: 192.168.129.2

  broker1:
    image: wurstmeister/kafka:2.13-2.7.0
    container_name: try-kafka_broker1
    # ports:
    # - '9092:9092'
    # - '9997:9997'
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 192.168.129.3
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://192.168.129.3:9092
      KAFKA_MESSAGE_MAX_BYTES: 2000000
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      # KAFKA_JMX_OPTS: '-Dcom.sun.management.jmxremote -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.ssl=false -Djava.rmi.server.hostname=192.168.1.12 -Dcom.sun.management.jmxremote.rmi.port=9997'
      # JMX_PORT: 9997
    volumes:
      - ./kafka-logs-1:/kafka
      - /var/run/docker.sock:/var/run/docker-kafka.sock
    networks:
      kf_net:
        ipv4_address: 192.168.129.3

  broker2:
    image: wurstmeister/kafka:2.13-2.7.0
    container_name: try-kafka_broker2
    # ports:
    #   - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 192.168.129.4
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://192.168.129.4:9092
      KAFKA_MESSAGE_MAX_BYTES: 2000000
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - ./kafka-logs-2:/kafka
      - /var/run/docker.sock:/var/run/docker-kafka.sock
    networks:
      kf_net:
        ipv4_address: 192.168.129.4

  broker3:
    image: wurstmeister/kafka:2.13-2.7.0
    container_name: try-kafka_broker3
    # ports:
    #   - "9092:9092"
    # - '9999:9997'
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 192.168.129.5
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://192.168.129.5:9092
      KAFKA_MESSAGE_MAX_BYTES: 2000000
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - ./kafka-logs-3:/kafka
      - /var/run/docker.sock:/var/run/docker-kafka.sock
    networks:
      kf_net:
        ipv4_address: 192.168.129.5

  # kafka-manager:
  #   image: kafkamanager/kafka-manager:3.0.0.4
  #   ports:
  #     - 9020:9000
  #   environment:
  #     ZK_HOSTS: zookeeper:2181
  #   networks:
  #     kf_net:
  #       ipv4_address: 192.168.129.10

  tester:
    image: tms/kafka-tester
    build:
      context: .
      dockerfile: Dockerfile-tester
    container_name: try-kafka_tester
    volumes:
      - ./docker/tester.py:/home
    networks:
      kf_net:
        ipv4_address: 192.168.129.6

networks:
  kf_net:
    ipam:
      driver: default
      config:
        - subnet: '192.168.129.0/24'
