FROM python:3.9.6-alpine3.14

# 设置时区
RUN apk update \
    && apk add -U tzdata \
    && cp /usr/share/zoneinfo/Asia/Shanghai /etc/localtime \
    && echo "Asia/Shanghai" > /etc/timezone \
    && apk del tzdata

# 安装依赖包
RUN pip install kafka-python jsonschema jsonpath-ng

WORKDIR /home

COPY ./src/logging.conf /home/conf/logging.conf

COPY ./src/tester.py /home/tester.py

RUN chmod a+x /home/tester.py
